# Generated by Django 5.0.4 on 2024-04-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHelp', '0002_alter_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='subtype',
            field=models.CharField(choices=[('EvenClub', 'EvenClub'), ('EventSocial', 'EventSocial')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='subject',
            field=models.CharField(default='', max_length=255),
        ),
    ]
