# Generated by Django 5.0.4 on 2024-04-30 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHelp', '0003_evenement_subtype_alter_stage_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='post',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='StudentHelp.post'),
        ),
        migrations.AddField(
            model_name='transport',
            name='post',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='StudentHelp.post'),
        ),
    ]
