# Generated by Django 5.0.4 on 2024-05-02 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHelp', '0005_post_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
    ]
