# Generated by Django 5.0.4 on 2024-05-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHelp', '0006_remove_post_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
