# Generated by Django 5.0.4 on 2024-05-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHelp', '0007_post_likes_alter_reaction_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AlterField(
            model_name='reaction',
            name='like',
            field=models.BooleanField(),
        ),
    ]
