# Generated by Django 5.0.4 on 2024-05-06 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHelp', '0011_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
