# Generated by Django 5.0.4 on 2024-05-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHelp', '0012_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='request_seen',
            field=models.BooleanField(default=False),
        ),
    ]
