# Generated by Django 5.0.4 on 2024-05-06 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHelp', '0013_transport_request_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='request_seen',
        ),
    ]
