# Generated by Django 5.0.4 on 2024-05-06 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHelp', '0015_transportrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransportRequest',
        ),
    ]
