# Generated by Django 5.0.4 on 2024-05-07 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHelp', '0017_transportrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportrequest',
            name='seats_needed',
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='StudentHelp.post'),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
