# Generated by Django 5.0.4 on 2024-05-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHelp', '0018_remove_transportrequest_seats_needed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportrequest',
            name='post',
        ),
        migrations.RemoveField(
            model_name='transportrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='seats_needed',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
