# Generated by Django 5.0.4 on 2024-05-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHelp', '0019_remove_transportrequest_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportrequest',
            name='seats_needed',
            field=models.IntegerField(default=0),
        ),
    ]
