# Generated by Django 5.0.4 on 2024-05-07 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHelp', '0020_alter_transportrequest_seats_needed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransportRequest',
        ),
    ]
