# Generated by Django 5.0.4 on 2024-05-07 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHelp', '0022_transportrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransportRequest',
        ),
    ]
