# Generated by Django 5.0.4 on 2024-05-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHelp', '0026_alter_transportrequest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportrequest',
            name='user',
        ),
    ]
